# Generated by Django 6.0.1 on 2026-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
