# Generated by Django 5.2.5 on 2026-02-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentitem_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
