# Generated by Django 5.2.5 on 2026-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_contentitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
